apiVersion: v1
kind: Pod
metadata:
  name: pod5
spec:
  containers:
  - name: httpd-container   
    image: httpd
    ports:
    - containerPort: 8080

  - name: nginx-container
    image: nginx
    ports: 
    - containerPort: 80
